import Link from "next/link";
import type { BlogFaq } from "@/lib/blog";
import {
  ArticleCta,
  ArticleFaq,
  ArticleSection,
  QuickAnswer,
} from "@/components/blog/ArticleLayout";

export const hallucinationFaqs: BlogFaq[] = [
  {
    q: "Are legal specific AI tools safer than general chatbots?",
    a: 'Generally yes, purpose built legal research tools tend to hallucinate less often than consumer chatbots, largely because they\'re grounded in real case law databases. But "less often" still means real risk remains, verification is still required.',
  },
  {
    q: "Can hallucinations happen even with careful prompting?",
    a: "Yes. Better prompting reduces the chance but doesn't eliminate it. The only reliable safeguard is human verification of the actual output, not just careful input.",
  },
  {
    q: "Is this a reason to avoid AI tools in legal work?",
    a: "Not really. The firms having problems are mostly the ones using AI without a review process, not the ones using AI carefully. Avoiding AI entirely just means missing the productivity gains while competitors who use it responsibly pull ahead.",
  },
];

export function HallucinationsArticle() {
  return (
    <>
      <QuickAnswer>
        <p>
          AI hallucinations, fabricated case citations, quotes, or facts
          generated by AI tools, have already appeared in real court filings. In
          one recent case, seventeen separate U.S. court decisions on a single
          day noted suspected hallucinations. Most incidents traced back to solo
          practitioners or small firms without a verification process, not to
          the AI tools themselves. The fix isn&apos;t avoiding AI. It&apos;s
          requiring human review of every AI generated citation or claim before
          it leaves the firm.
        </p>
      </QuickAnswer>

      <ArticleSection title="What's Actually Happening">
        <p>
          Generative AI tools sometimes produce confident, well written text that
          is simply wrong. In legal work this can mean invented case citations,
          misquoted rulings, or fabricated facts that read as entirely
          plausible. This isn&apos;t a rare glitch. It&apos;s a known limitation
          of how these tools work, and it has already caused real professional
          embarrassment and sanctions.
        </p>
        <p>
          Even legal specific research tools aren&apos;t immune. Independent
          research found meaningful hallucination rates on purpose built legal
          research platforms, not just general chatbots. That&apos;s a lower
          rate than consumer tools, but still far from zero.
        </p>
      </ArticleSection>

      <ArticleSection title="Who's Most at Risk">
        <p>
          The pattern is clear: incidents concentrate heavily among solo
          practitioners and small firms, often cases where the firm has no
          formal review process for AI generated content. Larger firms with
          structured AI governance see fewer incidents, not because their AI is
          better, but because their process catches mistakes before filing.
        </p>
        <p>
          This matters directly for smaller EU firms. The tools are accessible
          to everyone now. The safeguards are what separate firms that use AI
          safely from firms that end up in the news for the wrong reason.
        </p>
      </ArticleSection>

      <ArticleSection title="Why This Happens">
        <p>
          AI language models generate text by predicting what&apos;s
          statistically likely to come next, not by retrieving verified facts
          from a database. When a model doesn&apos;t have a real answer, it can
          still generate something that looks like one. For legal work, where a
          single fabricated citation can undermine an entire filing, this makes
          verification non negotiable.
        </p>
      </ArticleSection>

      <ArticleSection title="What Safe Usage Actually Looks Like">
        <p>
          A workable process for avoiding hallucination risk usually includes:
        </p>
        <ul className="list-disc space-y-3 pl-5">
          <li>
            Treating every AI generated citation as unverified until checked
            against a primary source
          </li>
          <li>
            Never filing AI drafted content without a human reading every
            citation and quote
          </li>
          <li>
            Using tools with source linking or citation verification features
            where available
          </li>
          <li>
            Training junior staff specifically on this risk, not assuming
            it&apos;s obvious
          </li>
          <li>
            Building a simple checklist step into your firm&apos;s document
            workflow rather than relying on individual diligence
          </li>
        </ul>
      </ArticleSection>

      <ArticleFaq faqs={hallucinationFaqs} />

      <ArticleCta>
        <p>
          AI hallucination risk in legal work is real, documented, and already
          affecting real cases. It&apos;s also entirely manageable with the
          right process. The firms getting into trouble aren&apos;t the ones
          using AI. They&apos;re the ones using it without a verification habit
          built into their workflow.
        </p>
        <p>
          Not sure whether your firm&apos;s current AI usage has the right
          safeguards in place? Our{" "}
          <Link href="/" className="underline underline-offset-4">
            AI Tools Assessment
          </Link>{" "}
          reviews your workflows and flags where verification gaps exist before
          they become a problem.
        </p>
      </ArticleCta>
    </>
  );
}
